project:
  type: website

website:
  title: "Tu blog"
  favicon: favicon.svg
  site-url: https://diezvariante.cl/blog
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Transporte"
        href: categorias/transporte.qmd
      - text: "Eléctrica"
        href: categorias/electrica.qmd
      - text: "Música"
        href: categorias/musica.qmd
      - text: "Fotos"
        href: categorias/fotos.qmd
      - text: "Otros"
        href: categorias/otros.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Pablolog42/blog
        aria-label: GitHub

format:
  html:
    theme:
      light: [litera, custom.scss]
      dark: [darkly, dark.scss]
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    fontsize: 1.05em
    smooth-scroll: true
